stages:
  - lint
  - build
  - package
  - publish

pre-commit:
    stage: lint
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    image: registry.gitlab.com/cahuteproject/docker-images/pre-commit:latest
    script:
        - pre-commit run -v --all-files

build (x86_64-pc-linux-gnu):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/x86_64-pc-linux-gnu:latest
    script:
        - >
            cmake -B build-x86_64-pc-linux-gnu -S .
            -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build-x86_64-pc-linux-gnu

build (arm-pc-linux-gnueabihf):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/arm-pc-linux-gnueabihf:latest
    script:
        - >
            cmake -B build-arm-pc-linux-gnueabihf -S .
            -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build-arm-pc-linux-gnueabihf

build (arm-pc-linux-musleabihf):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/arm-pc-linux-musleabihf:latest
    script:
        - >
            cmake -B build-arm-pc-linux-musleabihf -S .
            -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build-arm-pc-linux-musleabihf

build (i686-w64-mingw32-msvcrt):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/i686-w64-mingw32-msvcrt:latest
    script:
        - >
            cmake -B build-i686-w64-mingw32-msvcrt -S .
            -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build-i686-w64-mingw32-msvcrt

build (i686-w64-mingw32-ucrt):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/i686-w64-mingw32-ucrt:latest
    script:
        - >
            cmake -B build-i686-w64-mingw32-ucrt -S .
            -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build-i686-w64-mingw32-ucrt

build (x86_64-w64-mingw32-msvcrt):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/x86_64-w64-mingw32-msvcrt:latest
    script:
        - >
            cmake -B build-x86_64-w64-mingw32-msvcrt -S .
            -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build-x86_64-w64-mingw32-msvcrt

build (x86_64-w64-mingw32-ucrt):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/x86_64-w64-mingw32-ucrt:latest
    script:
        - >
            cmake -B build-x86_64-w64-mingw32-ucrt -S .
            -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build-x86_64-w64-mingw32-ucrt

build (m68k-amigaos):
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "chars/**/*"
          - "cli/**/*"
          - "common/**/*"
          - "include/**/*"
          - "lib/**/*"
          - ".gitlab-ci.yml"
    image: amigadev/crosstools:m68k-amigaos
    before_script:
        - apt-get update -y && apt-get install -y python3 python3-toml
    script:
        - cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCAHUTE_CLI_EXPERIMENTAL=ON
        - cmake --build build

.build docs:
    stage: build
    image: registry.gitlab.com/cahuteproject/docker-images/sphinx:latest
    script:
        - sphinx-build -M html docs docs/_build
    artifacts:
        paths:
            - docs/_build/html

build next docs:
    extends: .build docs
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - "docs/**/*"
          - ".gitlab-ci.yml"
    variables:
        IS_PREVIEW: "y"

build release docs:
    extends: .build docs
    rules:
        - if: $CI_COMMIT_TAG

package source:
    stage: package
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          changes:
          - ".gitlab-ci.yml"
    image: registry.gitlab.com/cahuteproject/docker-images/package-source:latest
    script:
        - >
            cmake -B build -S .
            -DCAHUTE_CLI=OFF -DCAHUTE_GIT=OFF -DCAHUTE_LIBUSB=OFF
            -DCAHUTE_PKGCONF=OFF -DCAHUTE_SDL=OFF -DCAHUTE_UDEV=OFF
        - cpack --config build/CPackSourceConfig.cmake
    artifacts:
        paths:
            - cahute-*.tar.gz

.publish docs:
    stage: publish
    image: registry.gitlab.com/cahuteproject/docker-images/rsync:latest
    before_script:
        - chmod 400 "$SSH_PRIVATE_KEY"
        - ssh-add "$SSH_PRIVATE_KEY"
    script:
        - rsync -Prlt --delete docs/_build/html/ $UPLOAD_PATH
    dependencies:
        - build docs

publish next docs:
    extends: .publish docs
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
        - if: $CI_COMMIT_TAG
    variables:
        UPLOAD_PATH: "$CAHUTE_NEXT_UPLOAD_PATH"
    dependencies:
        - build next docs

publish release docs:
    extends: .publish docs
    rules:
        - if: $CI_COMMIT_TAG
    variables:
        UPLOAD_PATH: "$CAHUTE_DOCS_UPLOAD_PATH"
    dependencies:
        - build release docs

publish source:
    stage: publish
    rules:
        - if: $CI_COMMIT_TAG
          when: always
    image: registry.gitlab.com/cahuteproject/docker-images/rsync:latest
    before_script:
        - chmod 400 "$SSH_PRIVATE_KEY"
        - ssh-add "$SSH_PRIVATE_KEY"
    script:
        - export RELEASE_FILE=$(ls cahute-*.tar.gz)
        - sha256sum $RELEASE_FILE >$RELEASE_FILE.sha256
        - b2sum $RELEASE_FILE >$RELEASE_FILE.b2
        - >
            scp $RELEASE_FILE $RELEASE_FILE.sha256 $RELEASE_FILE.b2
            $CAHUTE_FTP_UPLOAD_PATH/releases
    dependencies:
        - package source
